### ISSUE TITLE
Require requirejs by node failed.

### ISSUE THREAD

**Issue by chenp1204** [requirejs/requirejs#1681]
Please look the following photo, require requirejs by node failed.
--requirejs version 2.3.3

![qq 20170614222117](https://user-images.githubusercontent.com/29192482/27137435-86c76ddc-5150-11e7-9e87-2f29efcd7c4a.png)

**Comment by XEonAX** [comment]
I am also facing this issue. require('requirejs') throws:
`TypeError: Cannot set property 'requirejsVars' of undefined
    at j:\ROOT\BITSProject\jar-web\node_modules\requirejs\bin\r.js:2399:24
    at Object.<anonymous> (j:\ROOT\BITSProject\jar-web\node_modules\requirejs\bin\r.js:28749:2)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (j:\ROOT\BITSProject\jar-web\app.js:11:11)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)`
